spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/agro_master}
spring.datasource.username=${POSTGRES_USER:agro}
spring.datasource.password=${POSTGRES_PASSWORD:agro_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.default_schema=contact_service
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

server.port=8086

springdoc.api-docs.path=/api/docs/openapi
springdoc.swagger-ui.path=/api/docs/swagger

management.endpoints.web.exposure.include=health,info




